services:
  app:
    container_name: tz_wallet_app
    build:
      context: .
    ports:
      - "9999:80"
    depends_on:
      - db
    restart: always
    env_file:
      - .env

  db:
    container_name: tz_wallet_db
    image: postgres:latest
    ports:
      - "5428:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - tz_wallet_network
    env_file:
      - .env

#  redis:
#    image: redis:latest
#    container_name: tz_wallet_redis
#    ports:
#      - "6377:6379"
#    restart: always
#    volumes:
#      - tz_auth-redis-data:/data
#      - ./redis.conf:/usr/local/etc/redis/redis.conf
#      - ./users.acl:/usr/local/etc/redis/users.acl
#    env_file:
#      - .env
#    networks:
#      - tz_auth_network
#    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

volumes:
#  tz_auth-redis-data:
  postgres_data:

networks:
  tz_wallet_network:
    driver: bridge