"""Changed enum name in Operation model

Revision ID: 0fe56d909b6b
Revises: 636f1d89a773
Create Date: 2025-12-09 21:46:14.453415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0fe56d909b6b'
down_revision: Union[str, None] = '636f1d89a773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('operations', 'operation_type',
               existing_type=postgresql.ENUM('DEPOSIT', 'WITHDRAW', name='walletoperation'),
               type_=sa.Enum('DEPOSIT', 'WITHDRAW', name='operationtypeenum'),
               existing_comment='Operation type',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('operations', 'operation_type',
               existing_type=sa.Enum('DEPOSIT', 'WITHDRAW', name='operationtypeenum'),
               type_=postgresql.ENUM('DEPOSIT', 'WITHDRAW', name='walletoperation'),
               existing_comment='Operation type',
               existing_nullable=False)
    # ### end Alembic commands ###
