"""Renamed field in Wallet model

Revision ID: 5ef0096c9135
Revises: 0fe56d909b6b
Create Date: 2025-12-10 14:45:06.693179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ef0096c9135'
down_revision: Union[str, None] = '0fe56d909b6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operations', sa.Column('amount', sa.Float(), nullable=False, comment='Operation type'))
    op.add_column('wallet', sa.Column('total_amount', sa.Float(), nullable=False))
    op.drop_column('wallet', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('wallet', 'total_amount')
    op.drop_column('operations', 'amount')
    # ### end Alembic commands ###
