"""Added Operation model

Revision ID: 636f1d89a773
Revises: 5e7d3a004a0f
Create Date: 2025-12-09 17:42:51.439010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '636f1d89a773'
down_revision: Union[str, None] = '5e7d3a004a0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_type', sa.Enum('DEPOSIT', 'WITHDRAW', name='walletoperation'), nullable=False, comment='Operation type'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('wallet_sid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['wallet_sid'], ['wallet.sid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operations_id'), 'operations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operations_id'), table_name='operations')
    op.drop_table('operations')
    # ### end Alembic commands ###
