"""Added default value for 'total_amount'

Revision ID: 86716c1415b6
Revises: f4f08de69e55
Create Date: 2025-12-10 20:50:50.665689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86716c1415b6'
down_revision: Union[str, None] = 'f4f08de69e55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
