"""Added Wallet model

Revision ID: a9fe180e2467
Revises: 3c3422b2b004
Create Date: 2025-12-08 17:27:09.113117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9fe180e2467'
down_revision: Union[str, None] = '3c3422b2b004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet',
    sa.Column('sid', sa.Uuid(), nullable=False),
    sa.Column('user_sid', sa.Uuid(), nullable=False),
    sa.Column('operation_type', sa.Enum('DEPOSIT', 'WITHDRAW', name='walletoperation'), nullable=False, comment='Operation type'),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_sid'], ['user.sid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_index(op.f('ix_wallet_sid'), 'wallet', ['sid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_sid'), table_name='wallet')
    op.drop_table('wallet')
    # ### end Alembic commands ###
